version: '3.8'

services:
  backend:
    build: 
      context: ./rust
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8080:8080"
    volumes:
      - todo-data:/app/data
    networks:
      - app-network
    environment:
      - RUST_LOG=debug
    # Health check ekleyelim
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/todos"]
      interval: 30s
      timeout: 10s
      retries: 3

  music-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: music-service
    ports:
      - "8000:8000"
    volumes:
      - ./python:/app
      - music-data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/stream"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
      - VITE_MUSIC_URL=http://localhost:8000
    volumes:
      - ./react:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
      music-service:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  todo-data:
  music-data: